name: CD
description: |
  説明です

on:
  pull_request:
    types:
      - closed

jobs:
  depdeploy:
    name: デプロイ
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    environment:
      name: lab
      url: https://www.sample.example.com/
    steps:
    - name: Checkout application repository
      uses: actions/checkout@v5
    - name: Checkout application repository
      run: |
        echo The PR was merged
    - name: set Deploy URL
      run: |
        # デプロイ処理を書く（例: Vercel CLI, Netlify CLIなど）
        # CLIでURLを取得して echo "DEPLOYMENT_URL=取得したURL" >> $GITHUB_ENV
        echo "DEPLOYMENT_URL=https://example.vercel.app" >> $GITHUB_ENV
